<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
    .header { background: #1e293b; color: white; padding: 16px 20px; margin-bottom: 16px; }
    .header h1 { font-size: 16px; font-weight: bold; }
    .header p  { font-size: 10px; opacity: 0.8; margin-top: 4px; }
    .meta { padding: 0 20px 12px; display: flex; gap: 20px; }
    .meta span { background: #f1f5f9; padding: 4px 10px;
                 border-radius: 4px; font-size: 10px; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; }
    th { background: #334155; color: white; padding: 7px 10px;
         text-align: left; font-weight: bold; }
    td { padding: 6px 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .badge { padding: 2px 7px; border-radius: 10px;
             font-size: 9px; font-weight: bold; }
    .in-stock  { background: #dcfce7; color: #15803d; }
    .low-stock { background: #fef9c3; color: #a16207; }
    .out-stock { background: #fee2e2; color: #b91c1c; }
    .footer { margin-top: 16px; padding: 8px 20px;
              border-top: 1px solid #e2e8f0; font-size: 9px; color: #64748b; }
    .summary { padding: 0 20px 12px; display: flex; gap: 12px; }
    .summary-box { border: 1px solid #e2e8f0; border-radius: 6px;
                   padding: 8px 16px; text-align: center; min-width: 80px; }
    .summary-box .num { font-size: 18px; font-weight: bold; }
    .summary-box .lbl { font-size: 9px; color: #64748b; }
</style>
</head>
<body>

<div class="header">
    <h1>📦 Inventory Status Report</h1>
    <p>Inventory Management System &mdash; Generated: {{ now()->format('F d, Y h:i A') }}</p>
</div>

<div class="summary">
    <div class="summary-box">
        <div class="num">{{ $inventories->count() }}</div>
        <div class="lbl">Total Items</div>
    </div>
    <div class="summary-box">
        <div class="num" style="color:#15803d">{{ $inStock }}</div>
        <div class="lbl">In Stock</div>
    </div>
    <div class="summary-box">
        <div class="num" style="color:#a16207">{{ $lowStock }}</div>
        <div class="lbl">Low Stock</div>
    </div>
    <div class="summary-box">
        <div class="num" style="color:#b91c1c">{{ $outOfStock }}</div>
        <div class="lbl">Out of Stock</div>
    </div>
    <div class="summary-box">
        <div class="num">{{ number_format($totalValue, 2) }}</div>
        <div class="lbl">Total Value (₱)</div>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>SKU</th>
            <th>Product Name</th>
            <th>Category</th>
            <th>Supplier</th>
            <th>Location</th>
            <th style="text-align:center">Qty</th>
            <th style="text-align:center">Reorder</th>
            <th style="text-align:center">Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($inventories as $i => $inv)
        @php
            $qty    = $inv->quantity;
            $reorder = $inv->product->reorder_level;
        @endphp
        <tr>
            <td>{{ $i + 1 }}</td>
            <td>{{ $inv->product->sku }}</td>
            <td>{{ $inv->product->name }}</td>
            <td>{{ $inv->product->category }}</td>
            <td>{{ $inv->product->supplier->name ?? '—' }}</td>
            <td>{{ $inv->location ?? '—' }}</td>
            <td style="text-align:center;font-weight:bold">{{ $qty }}</td>
            <td style="text-align:center">{{ $reorder }}</td>
            <td style="text-align:center">
                @if($qty === 0)
                    <span class="badge out-stock">Out of Stock</span>
                @elseif($qty <= $reorder)
                    <span class="badge low-stock">Low Stock</span>
                @else
                    <span class="badge in-stock">In Stock</span>
                @endif
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    <strong>Inventory Management System</strong> &mdash;
    Report generated by {{ auth()->user()->name }} on
    {{ now()->format('F d, Y') }} &mdash; Total records: {{ $inventories->count() }}
</div>

</body>
</html>