<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
    .header { background: #1e293b; color: white; padding: 16px 20px; margin-bottom: 16px; }
    .header h1 { font-size: 16px; font-weight: bold; }
    .header p  { font-size: 10px; opacity: 0.8; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; }
    th { background: #334155; color: white; padding: 7px 10px; text-align: left; }
    td { padding: 6px 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .badge { padding: 2px 6px; border-radius: 10px; font-size: 9px; font-weight: bold; }
    .in  { background: #dcfce7; color: #15803d; }
    .out { background: #fee2e2; color: #b91c1c; }
    .adj { background: #fef9c3; color: #a16207; }
    .footer { margin-top: 16px; padding: 8px 20px;
              border-top: 1px solid #e2e8f0; font-size: 9px; color: #64748b; }
    .filters { padding: 0 20px 12px; font-size: 10px; color: #64748b; }
</style>
</head>
<body>

<div class="header">
    <h1>🔄 Stock Movements Report</h1>
    <p>Generated: {{ now()->format('F d, Y h:i A') }}</p>
</div>

<div class="filters">
    @if($filters['type'])
        <strong>Type:</strong> {{ ucfirst($filters['type']) }} &nbsp;
    @endif
    @if($filters['date_from'])
        <strong>From:</strong> {{ $filters['date_from'] }} &nbsp;
    @endif
    @if($filters['date_to'])
        <strong>To:</strong> {{ $filters['date_to'] }} &nbsp;
    @endif
    @if(!array_filter($filters))
        All movements
    @endif
</div>

<table>
    <thead>
        <tr>
            <th>Ref #</th>
            <th>Date</th>
            <th>Product</th>
            <th>SKU</th>
            <th style="text-align:center">Type</th>
            <th style="text-align:center">Quantity</th>
            <th>Reason</th>
            <th>By</th>
        </tr>
    </thead>
    <tbody>
        @foreach($movements as $m)
        <tr>
            <td>#{{ $m->id }}</td>
            <td>{{ $m->created_at->format('M d, Y') }}</td>
            <td>{{ $m->product->name }}</td>
            <td>{{ $m->product->sku }}</td>
            <td style="text-align:center">
                @if($m->type === 'in')
                    <span class="badge in">Stock In</span>
                @elseif($m->type === 'out')
                    <span class="badge out">Stock Out</span>
                @else
                    <span class="badge adj">Adjustment</span>
                @endif
            </td>
            <td style="text-align:center;font-weight:bold;
                color:{{ $m->type === 'out' ? '#b91c1c' : '#15803d' }}">
                {{ $m->type === 'out' ? '−' : '+' }}{{ abs($m->quantity) }}
            </td>
            <td>{{ $m->reason ?? '—' }}</td>
            <td>{{ $m->user->name ?? '—' }}</td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    <strong>Inventory Management System</strong> &mdash;
    Generated by {{ auth()->user()->name }} &mdash;
    Total records: {{ $movements->count() }}
</div>

</body>
</html>