<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; }
    .header { background: #1e293b; color: white; padding: 16px 20px; margin-bottom: 16px; }
    .header h1 { font-size: 16px; font-weight: bold; }
    .header p  { font-size: 10px; opacity: 0.8; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; }
    th { background: #334155; color: white; padding: 7px 10px; text-align: left; }
    td { padding: 6px 10px; border-bottom: 1px solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .badge { padding: 2px 6px; border-radius: 10px; font-size: 9px; font-weight: bold; }
    .active   { background: #dcfce7; color: #15803d; }
    .inactive { background: #f1f5f9; color: #64748b; }
    .footer { margin-top: 16px; padding: 8px 20px;
              border-top: 1px solid #e2e8f0; font-size: 9px; color: #64748b; }
</style>
</head>
<body>

<div class="header">
    <h1>🏭 Suppliers Report</h1>
    <p>Generated: {{ now()->format('F d, Y h:i A') }}</p>
</div>

<table>
    <thead>
        <tr>
            <th>#</th>
            <th>Company Name</th>
            <th>Contact Person</th>
            <th>Email</th>
            <th>Phone</th>
            <th style="text-align:center">Products</th>
            <th style="text-align:center">Status</th>
        </tr>
    </thead>
    <tbody>
        @foreach($suppliers as $i => $supplier)
        <tr>
            <td>{{ $i + 1 }}</td>
            <td><strong>{{ $supplier->name }}</strong></td>
            <td>{{ $supplier->contact_person }}</td>
            <td>{{ $supplier->email }}</td>
            <td>{{ $supplier->phone }}</td>
            <td style="text-align:center">{{ $supplier->products_count }}</td>
            <td style="text-align:center">
                <span class="badge {{ $supplier->status }}">
                    {{ ucfirst($supplier->status) }}
                </span>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

<div class="footer">
    <strong>Inventory Management System</strong> &mdash;
    Generated by {{ auth()->user()->name }} &mdash;
    Total: {{ $suppliers->count() }} suppliers
</div>

</body>
</html>